### ISSUE TITLE
Build-time socket connections?

### ISSUE THREAD

**Issue by xach** [tani/cl-skkserv#2]
It looks like this project tries to make a build-time connection to openlab.ring.gr.jp - why is that? Is it required? Yesterday the connection was refused, so the build failed.

**Comment by tani** [comment]
It is downloading a latest disctionary file which is used when cl-skkserv converts from hiragana to kanji. cl-skkserv needs downloading the file once. So I could change the behavior. I’m going to change the time so that cl-skkserv will download it at that we launch this program.

**Comment by xach** [comment]
This remains a problem for me. I can't reach the server when the project is built.

**Comment by tani** [comment]
@xach we stop downloading dictionary data. I guess you can build this project.
Thanks.
