### ISSUE TITLE
THe tests assume the current directory

### ISSUE THREAD

**Issue by Yehouda** [tani/cl-skkserv#3]
The tests assume that that the current directory is the system directory when they use relative pathname to access the dictionary. That is not correct assumption,. 

The best way to fix is to use **asdf/system:system-relative-pathname**. For example, change the definition of **\*lisp-dictionary\*** in tests/skk.lisp to : 

```
(defparameter \*lisp-dictionary\* 
     (make-instance 
         'skk-lisp-dictionary
          :pathname (asdf/system:system-relative-pathname 
                              "cl-skkserv/tests"  "data/SKK-JISYO.L" )))
```

**Comment by tani** [comment]
Thank you. I do that now.

**Comment by tani** [comment]
Thank you for the contribution! I fixed it.

**Comment by Yehouda** [comment]
The fix is incomplete. The same fix that was done in test/skk.lisp is needed in test/mixed.lisp (twice)  and tets/core.lisp

https://github.com/tani/cl-skkserv/blob/81bd164a15ab134b838ea10d17cac483928ad730/test/mixed.lisp#L10
https://github.com/tani/cl-skkserv/blob/81bd164a15ab134b838ea10d17cac483928ad730/test/mixed.lisp#L12
https://github.com/tani/cl-skkserv/blob/81bd164a15ab134b838ea10d17cac483928ad730/test/core.lisp#L8
